name: check

on:
  push:
    branches: 
      - master
  
  workflow_dispatch:

jobs:
  my_check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: print hello message
        run: echo "Hello, world!"

      - name: print multi-line message
        run: |
          echo "This \
          multi-line"
          echo "message"
