name: check
env:
  name: "Peter"

on:
  push:
    branches: [master]
  
  workflow_dispatch:

jobs:
  my_check:
    runs-on: ubuntu-latest
    
    steps:
      - name: list of folder
        run: ls -la
      
      - name: Git clone my repository
        uses: actions/checkout@v2
      
      - name: and at now
        run: ls -la
      
      - name: print hello message in check
        run: echo "Hello, ${{ env.name }}"
  
  my_test:
    runs-on: ubuntu-latest
    needs: [my_check]
    
    steps:
      - name: print multi-line message in test
        run: |
          echo "This multi-line"
          echo "message"
